In [12]:
import math as mh
import multiprocessing as mg
import multiprocessing.pool
# import pys2let as ps
import random
import string
import itertools
import os

import jax
jax.config.update("jax_enable_x64", True)
import s2fft
import healpy as hp
import numpy as np
import s2wav
import s2wav
import matplotlib.pyplot as plt
%matplotlib inline 
import skyclean
from skyclean import CMB_data

In [10]:
# In Pixel space

stored_wavelet_coeffs_pix = [np.load(f"../convolution/wavelet_coefficient/wav_30_{i}.npy", allow_pickle=True) for i in range(12)]
stored_scaling_coeffs_pix = np.load("../convolution/scaling_coefficient/scal_30.npy")

In [20]:
# The extra dimension for the wavelet coefficients is for spin?
# Convert wavelet coefficient from MW pixel space to MW alm space
stored_wavelet_coeffs_pix[0].shape
stored_wavelet_coeffs_pix = stored_wavelet_coeffs_pix[:3]

stored_wavelet_coeffs_alm = []

for i in range(len(stored_wavelet_coeffs_pix)):
    print("Scale:",i,"original size", stored_wavelet_coeffs_pix[i].shape)
    stored_wavelet_coeffs_alm.append(s2fft.forward(stored_wavelet_coeffs_pix[i], L = stored_wavelet_coeffs_pix[i].shape[1]))
    print("Scale:",i,"alm size", stored_wavelet_coeffs_alm[i].shape)

print("finished converting wavelet coefficient from MW pixel to MW alm space")

stored_wavelet_coeffs_alm_doubled = []
for i in range(len(stored_wavelet_coeffs_alm)):
    print("Scale:",i,"original alm size", stored_wavelet_coeffs_alm[i].shape)
    padded_alm = np.zeros((stored_wavelet_coeffs_alm[i].shape[0]*2,stored_wavelet_coeffs_alm[i].shape[1]))
    # stored_wavelet_coeffs_alm_doubled.append(skyclean.double_resolution(stored_wavelet_coeffs_alm[i]))
    padded_alm[:stored_wavelet_coeffs_alm[i].shape[0], :] = stored_wavelet_coeffs_alm[i]
    print("Scale:",i,"padded alm size", padded_alm.shape)
    stored_wavelet_coeffs_alm_doubled.append(padded_alm)
    # print(padded_alm)

Scale: 0 original size (1, 4, 7)
Scale: 0 alm size (4, 7)
Scale: 1 original size (1, 4, 7)
Scale: 1 alm size (4, 7)
Scale: 2 original size (1, 8, 15)
Scale: 2 alm size (8, 15)
finished converting wavelet coefficient from MW pixel to MW alm space
Scale: 0 original alm size (4, 7)
Scale: 0 padded alm size (8, 7)
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.14210811e-20
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.45611893e-04 -5.17021112e-06
  -2.45611893e-04  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.69276349e-20  1.49602346e-20  1.16208965e-20
  -2.03031756e-20 -2.37419590e-20  0.00000000e+00]
 [-2.86090616e-20  2.06983385e-20  5.81610474e-20 -5.84771400e-21
  -3.03448943e-20  7.35972185e-21  7.89309867e-21]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.

In [13]:
import numpy as np

# Example arrays of different shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10], [11, 12]])

# Find the shape of the resulting array
rows = max(array1.shape[0], array2.shape[0])
cols = max(array1.shape[1], array2.shape[1])

# Initialize arrays with zeros of the desired shape
padded_array1 = np.zeros((rows, cols))
padded_array2 = np.zeros((rows, cols))

# Fill the padded arrays with the original values
padded_array1[:array1.shape[0], :array1.shape[1]] = array1
padded_array2[:array2.shape[0], :array2.shape[1]] = array2

# Adding the padded arrays
result = padded_array1 + padded_array2

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Padded Array 1:")
print(padded_array1)
print("Padded Array 2:")
print(padded_array2)
print("Result of adding Padded Array 1 and Padded Array 2:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[ 7  8]
 [ 9 10]
 [11 12]]
Padded Array 1:
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]]
Padded Array 2:
[[ 7.  8.  0.]
 [ 9. 10.  0.]
 [11. 12.  0.]]
Result of adding Padded Array 1 and Padded Array 2:
[[ 8. 10.  3.]
 [13. 15.  6.]
 [11. 12.  0.]]
