In [ ]:
import numpy as np

# thread = np.load("ILC/covariance_matrix/cov_MW_Pix2_F030_044_070_100_143_217_353_545_857_S0_R0000_Full.npy")
# multiprocess = np.load("ILC/covariance_matrix/cov_MW_Pix2_F030_044_070_100_143_217_353_545_857_S0_R0000_MP.npy")

# thread = np.load("ILC/wavelet_doubled/Wav_Pix2_F030_S6_R0000.npy")

# multiprocess = np.load("ILC/wavelet_doubled/Wav_Pix2_F030_S6_R0000_MP.npy")

# thread = sum(sum(sum(sum(np.load(f"ILC/covariance_matrix/half_original_0.npy")))))
# multiprocess = sum(sum(sum(sum(np.load(f"ILC/covariance_matrix/half_cov_1_0.npy")))))

# thread = np.load("ILC/covariance_matrix/half_original_0.npy")
# multiprocess = np.load("ILC/covariance_matrix/half_cov_1_0.npy")

thread = np.load("ILC/covariance_matrix/half_original_4.npy")
multiprocess = np.load("ILC/covariance_matrix/half_cov_1_4.npy")


In [36]:
thread == multiprocess

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [ ]:
print(thread.shape)
thread

array([[4.22927675e-10, 4.23040075e-10, 4.23153004e-10, ...,
        4.22607026e-10, 4.22709878e-10, 4.22817172e-10],
       [4.23064046e-10, 4.23433541e-10, 4.23810191e-10, ...,
        4.22051080e-10, 4.22368062e-10, 4.22707207e-10],
       [4.23450319e-10, 4.24116833e-10, 4.24804316e-10, ...,
        4.21684257e-10, 4.22224606e-10, 4.22816186e-10],
       ...,
       [4.02289307e-10, 4.02856875e-10, 4.03451141e-10, ...,
        4.00830000e-10, 4.01268577e-10, 4.01757254e-10],
       [4.02356682e-10, 4.02620082e-10, 4.02893279e-10, ...,
        4.01658750e-10, 4.01872979e-10, 4.02106577e-10],
       [4.02924740e-10, 4.02924740e-10, 4.02924740e-10, ...,
        4.02924740e-10, 4.02924740e-10, 4.02924740e-10]])

In [38]:
multiprocess

array([[4.22927675e-10, 4.23040075e-10, 4.23153004e-10, ...,
        4.22607026e-10, 4.22709878e-10, 4.22817172e-10],
       [4.23064046e-10, 4.23433541e-10, 4.23810191e-10, ...,
        4.22051080e-10, 4.22368062e-10, 4.22707207e-10],
       [4.23450319e-10, 4.24116833e-10, 4.24804316e-10, ...,
        4.21684257e-10, 4.22224606e-10, 4.22816186e-10],
       ...,
       [4.02289307e-10, 4.02856875e-10, 4.03451141e-10, ...,
        4.00830000e-10, 4.01268577e-10, 4.01757254e-10],
       [4.02356682e-10, 4.02620082e-10, 4.02893279e-10, ...,
        4.01658750e-10, 4.01872979e-10, 4.02106577e-10],
       [4.02924740e-10, 4.02924740e-10, 4.02924740e-10, ...,
        4.02924740e-10, 4.02924740e-10, 4.02924740e-10]])