In [1]:
import numpy as np

# Example arrays of different shapes
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10], [11, 12]])

# Find the shape of the resulting array
rows = max(array1.shape[0], array2.shape[0])
cols = max(array1.shape[1], array2.shape[1])

# Initialize arrays with zeros of the desired shape
padded_array1 = np.zeros((rows, cols))
padded_array2 = np.zeros((rows, cols))

# Fill the padded arrays with the original values
padded_array1[:array1.shape[0], :array1.shape[1]] = array1
padded_array2[:array2.shape[0], :array2.shape[1]] = array2

# Adding the padded arrays
result = padded_array1 + padded_array2

print("Array 1:")
print(array1)
print("Array 2:")
print(array2)
print("Padded Array 1:")
print(padded_array1)
print("Padded Array 2:")
print(padded_array2)
print("Result of adding Padded Array 1 and Padded Array 2:")
print(result)


Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[ 7  8]
 [ 9 10]
 [11 12]]
Padded Array 1:
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]]
Padded Array 2:
[[ 7.  8.  0.]
 [ 9. 10.  0.]
 [11. 12.  0.]]
Result of adding Padded Array 1 and Padded Array 2:
[[ 8. 10.  3.]
 [13. 15.  6.]
 [11. 12.  0.]]
